# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/philipp-baumann/precommit-r-nix
    rev: 71f194a0aef52d395f200023741c932d5ea4bf45
    hooks: 
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style, --cache-root=styler-perm]
        require_serial: true
    -   id: lintr
        exclude: >
          (?x)^(
          tests/testthat/test-fetchers\.R|
          vignettes/.*
          )$
    -   id: parsable-R
        exclude: > 
          (?x)^(
          tests/testthat/in/.*|
          )$
    -   id: no-browser-statement

default_stages: ["commit"]

ci:
    # skip: [consistent-release-tag, spell-check-ordered-exclude, pkgdown]
    autoupdate_schedule: monthly
