build_envs.Rmd:
  path: dev/build_envs.Rmd
  state: active
  R: R/find_rev.R
  tests: tests/testthat/test-find_rev.R
  vignettes: []
  inflate:
    flat_file: dev/build_envs.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
building_envs_with_rix.Rmd:
  path: dev/building_envs_with_rix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/building-reproducible-development-environments-with-rix.Rmd
  inflate:
    flat_file: dev/building_envs_with_rix.Rmd
    vignette_name: Building reproducible development environments with rix
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
data_doc.Rmd:
  path: dev/data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
non_interactive_use.Rmd:
  path: dev/non_interactive_use.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/non-interactive-use.Rmd
  inflate:
    flat_file: dev/non_interactive_use.Rmd
    vignette_name: Non-interactive use
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
save_r_nix_revs.Rmd:
  path: dev/save_r_nix_revs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/save-the-nix-package-versions-data.Rmd
  inflate:
    flat_file: dev/save_r_nix_revs.Rmd
    vignette_name: Save the Nix Package Versions data
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
zzz.Rmd:
  path: dev/zzz.Rmd
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/zzz.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
