build_envs.Rmd:
  path: dev/build_envs.Rmd
  state: active
  R: R/find_rev.R
  tests: tests/testthat/test-find_rev.R
  vignettes: vignettes/dev-build_envs.Rmd
  inflate:
    flat_file: dev/build_envs.Rmd
    vignette_name: dev-build_envs
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
data_doc.Rmd:
  path: dev/data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
save_r_nix_revs.Rmd:
  path: dev/save_r_nix_revs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/dev-save_r_nix_revs.Rmd
  inflate:
    flat_file: dev/save_r_nix_revs.Rmd
    vignette_name: dev-save_r_nix_revs
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
zzz.Rmd:
  path: dev/zzz.Rmd
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/zzz.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
