1-getting_started.Rmd:
  path: dev/1-getting_started.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/a-getting-started.Rmd
  inflate:
    flat_file: dev/1-getting_started.Rmd
    vignette_name: a - Getting started
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
2a-linux_win.Rmd:
  path: dev/2a-linux_win.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/b1-setting-up-and-using-rix-on-linux-and-windows.Rmd
  inflate:
    flat_file: dev/2a-linux_win.Rmd
    vignette_name: b1 - Setting up and using rix on Linux and Windows
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
2b-macos.Rmd:
  path: dev/2b-macos.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/b2-setting-up-and-using-rix-on-macos.Rmd
  inflate:
    flat_file: dev/2b-macos.Rmd
    vignette_name: b2 - Setting up and using rix on macOS
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
3-building_envs_with_rix.Rmd:
  path: dev/3-building_envs_with_rix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/c-using-rix-to-build-project-specific-environments.Rmd
  inflate:
    flat_file: dev/3-building_envs_with_rix.Rmd
    vignette_name: c - Using rix to build project specific environments
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
4a-install_r_pkgs.Rmd:
  path: dev/4a-install_r_pkgs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/d1-installing-r-packages-in-a-nix-environment.Rmd
  inflate:
    flat_file: dev/4a-install_r_pkgs.Rmd
    vignette_name: d1 - Installing R packages in a Nix environment
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
4b-install_sys_pkgs.Rmd:
  path: dev/4b-install_sys_pkgs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/d2-installing-system-tools-and-texlive-packages-in-a-nix-environment.Rmd
  inflate:
    flat_file: dev/4b-install_sys_pkgs.Rmd
    vignette_name: d2 - Installing system tools and TexLive packages in a Nix environment
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
5-interactive_use.Rmd:
  path: dev/5-interactive_use.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/e-interactive-use.Rmd
  inflate:
    flat_file: dev/5-interactive_use.Rmd
    vignette_name: e - Interactive use
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_build_envs.Rmd:
  path: dev/flat_build_envs.Rmd
  state: active
  R: R/find_rev.R
  tests: tests/testthat/test-find_rev.R
  vignettes: []
  inflate:
    flat_file: dev/flat_build_envs.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_cicd.Rmd:
  path: dev/flat_cicd.Rmd
  state: active
  R: R/tar_nix_ga.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_cicd.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_cran_archive.Rmd:
  path: dev/flat_cran_archive.Rmd
  state: active
  R: R/detect_versions.R
  tests: tests/testthat/test-detect_versions.R
  vignettes: []
  inflate:
    flat_file: dev/flat_cran_archive.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_data_doc.Rmd:
  path: dev/flat_data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_get_os.Rmd:
  path: dev/flat_get_os.Rmd
  state: active
  R: R/detect_os.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_get_os.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_save_r_nix_revs.Rmd:
  path: dev/flat_save_r_nix_revs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/developers-vignette-save-the-nix-package-versions-data.Rmd
  inflate:
    flat_file: dev/flat_save_r_nix_revs.Rmd
    vignette_name: 'Developers Vignette: Save the Nix Package Versions data'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_zzz.Rmd:
  path: dev/flat_zzz.Rmd
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_zzz.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
literate_programming.Rmd:
  path: dev/literate_programming.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-building-an-environment-for-literate-programming.Rmd
  inflate:
    flat_file: dev/literate_programming.Rmd
    vignette_name: 'z - Advanced topic: Building an environment for literate programming'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
pkgs_with_remotes.Rmd:
  path: dev/pkgs_with_remotes.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-handling-packages-with-remote-dependencies.Rmd
  inflate:
    flat_file: dev/pkgs_with_remotes.Rmd
    vignette_name: 'z - Advanced topic: Handling packages with remote dependencies'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
raps_with_nix.Rmd:
  path: dev/raps_with_nix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-reproducible-analytical-pipelines-with-nix.Rmd
  inflate:
    flat_file: dev/raps_with_nix.Rmd
    vignette_name: 'z - Advanced topic: Reproducible Analytical Pipelines with Nix'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
subshells.Rmd:
  path: dev/subshells.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-running-r-or-shell-code-in-nix-from-r.Rmd
  inflate:
    flat_file: dev/subshells.Rmd
    vignette_name: 'z - Advanced topic: Running R or Shell Code in Nix from R'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
