name: Check code
on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix
          # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH }}'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1
      - run: pre-commit clean
      - uses: pre-commit-ci/lite-action@v1.0.3
        name: pre-commit-ci-lite
        if: always()
        with:
          msg: check lints and apply code formatting
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
