on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: nix-builder

jobs:
  build:
    name: nix builder
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Run `nix-build ./inst/extdata/default.nix`
      run: |
        nix-build ./inst/extdata/default.nix
        nix-shell ./inst/extdata/default.nix
