# Run rhub checks
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: rhub-checks

permissions: write-all

jobs:
  devtools:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run checks
        run: nix-shell --run "Rscript -e \"rhub::rhub_check(platforms = c('linux','macos','macos-arm64','windows','ubuntu-next','ubuntu-release', branch = 'master'))\""
