# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: styler

permissions: write-all

jobs:
  style_pkg:
    runs-on: ubuntu-latest
    env:
     GH_TOKEN: ${{ github.token }}
     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Build dev env
        run: nix-build

      - name: Run styler::style_pkg
        run: nix-shell --run "Rscript -e 'styler::style_pkg()'"

      - name: Check if PR exists
        id: check_pr
        run: |
          PR=$(gh pr list -S 'Style package' --json number --jq '.[0].number')
          echo "PR_NUMBER=$PR" >> $GITHUB_ENV

      - name: Configure user and check for changes
        run: |
          git config --global user.email "ga-ci@no-reply.com"
          git config --global user.name "CI Robot"
          git diff-index --quiet HEAD || echo "has_changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git add .
          git commit -m "Styled package"
          git push origin master:style_pkg --force

      - name: Create Pull Request
        if: env.PR_NUMBER == ''
        uses: peter-evans/create-pull-request@v6
        with:
          branch: style_pkg
          title: 'Style package'
          body: 'Automated PR to style package using `styler:style_pkg()`'
          base: master
          branch-suffix: ''
